---

- name: install mysql
  yum: name={{item}} state=latest
  with_items:
    - MySQL-python
    - mysql-server
    - libselinux-python

- name: start mysql and enabled
  service: name=mysqld state=started enabled=yes

- name: copy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Create the database users
  mysql_user: name={{item.name}} password={{item.pass}} priv={{item.priv}} host={{item.host}} state=present
  with_items: mysql_users


# tasks for master
- name: Create the replication users
  mysql_user: name={{item.name}} password={{item.pass}} priv="*.*:REPLICATION SLAVE" host="%" state=present
  with_items: mysql_repl_user
  when: mysql_repl_role == "master"


# tasks for slave
- name: Get the current master servers replication status
  mysql_replication: mode=getmaster
  delegate_to: "mysql-master"
  register: repl_stat
  when: mysql_repl_role == "slave"

- name: Change the master in slave to start the replication
  mysql_replication: mode=changemaster master_host={{mysql_repl_master}} master_user={{mysql_repl_user[0].name}} master_password={{mysql_repl_user[0].pass}} master_log_file={{ repl_stat.File }} master_log_pos={{ repl_stat.Position }}
  when: mysql_repl_role == "slave"

- name: start slave
  mysql_replication: mode=startslave
  when: mysql_repl_role == "slave"

