---

- name: install apache
  yum: name=httpd state=latest

- name: start apache and enabled
  service: name=httpd state=started enabled=yes

- name: install php packages
  yum: name={{item}} state=latest
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql
  notify:
    - restart apache

- name: install git
  yum: name=git state=latest

