---

- name: add apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- name: add sources.list
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

- name: install MongoDB
  apt: name=mongodb-org state=present update_cache=yes

- name: start MongoDB
  service: name=mongod state=started enabled=yes
